# APP_PORT=9090 APP_SERVER_PORT=8083 MODEL_PORT=9091 MODEL_SERVICE_PORT=9093 docker-compose up
# Uses:
# - Host: 9090 → Container: 8083 (app)
# - Host: 9091 → Container: 9093 (model)
services:
  app-service:
    image: ghcr.io/doda2025-team17/app:latest
    container_name: app-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MODEL_SERVICE_URL=http://model-service:8081
    depends_on:
      - model-service
    networks:
      - sms-network

  model-service:
    image: ghcr.io/doda2025-team17/model-service:latest
    container_name: model-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MODEL_URL=https://github.com/doda2025-team17/model-service/releases/download/v1.0.0/model-artifacts.tar.gz #Change this URL if a new model is trained-and-released
    volumes:
      - model-data:/models
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge

volumes:
  model-data: