services:
  app-service:
    image: ghcr.io/doda2025-team17/app:latest
    container_name: app-service
    ports:
      - "${APP_HOST_PORT}:${APP_CONTAINER_PORT}"
    environment:
      - APP_SERVER_PORT=${APP_CONTAINER_PORT}
      - MODEL_HOST=http://model-service:${MODEL_CONTAINER_PORT}
    depends_on:
      - model-service
    networks:
      - sms-network

  model-service:
    image: ghcr.io/doda2025-team17/model-service:latest
    container_name: model-service
    ports:
      - "${MODEL_HOST_PORT}:${MODEL_CONTAINER_PORT}"
    environment:
      - MODEL_SERVICE_PORT=${MODEL_CONTAINER_PORT}
      - MODEL_URL=${MODEL_URL}
    volumes:
      - model-data:/models
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge

volumes:
  model-data:
