services:
  app-service:
    image: ghcr.io/doda2025-team17/app:latest
    container_name: app-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MODEL_HOST=http://model-service:8081
    depends_on:
      - model-service
    networks:
      - sms-network

  model-service:
    image: ghcr.io/doda2025-team17/model-service:latest
    container_name: model-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    volumes:
      - model-data:/app/output
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge

volumes:
  model-data: