# TODO: generate configmap.yaml from .env file? 
# But Helm will use values.yaml, so I'm not sure if it's necessary. I don't like the hardcoded values, though.
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sms-app
data:
  APP_HOST_PORT: "8080"
  APP_SERVER_PORT: "8080"
  MODEL_HOST: "http://model-service:8081"
  MODEL_SERVICE_PORT: "8081"
  MODEL_URL: "https://github.com/doda2025-team17/model-service/releases/download/v1.0.0/model-artifacts.tar.gz"
