# Helm should handle this later.
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: sms-app
type: Opaque
stringData:
  # Placeholder for SMTP password or other secrets
  SMTP_PASSWORD: "CHANGE_ME_IN_HELM"