apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sms-app.fullname" . }}-config
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "sms-app.labels" . | nindent 4 }}
data:
  APP_HOST_PORT: "{{ .Values.config.appHostPort }}"
  APP_SERVER_PORT: "{{ .Values.config.appServerPort | default (toString .Values.app.containerPort) }}"
  MODEL_HOST: "{{ .Values.config.modelHost | default (printf "http://%s:%v" (include "sms-app.model.name" .) .Values.modelService.service.port) }}"
  MODEL_SERVICE_PORT: "{{ .Values.config.modelServicePort | default (toString .Values.modelService.service.port) }}"
  MODEL_URL: "{{ .Values.config.modelUrl }}"
  DASHBOARD_VERSION: {{ .Values.config.dashboardVersion | default "v1" }}