{{- if and .Values.modelService.canary.enabled (not .Values.modelService.shadow.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sms-app.model.name" . }}-v2
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "sms-app.componentLabels" (dict "context" . "name" (printf "%s-v2" (include "sms-app.model.name" .)) "component" "model") | nindent 4 }}
spec:
  type: {{ .Values.modelService.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "sms-app.model.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    version: {{ .Values.modelService.canary.versionLabel | default "v2" | quote }}
  ports:
    - name: http
      port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.containerPort }}
{{- end }}