apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sms-app.model.name" . }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "sms-app.componentLabels" (dict "context" . "name" (include "sms-app.model.name" .) "component" "model") | nindent 4 }}
spec:
  replicas: {{ .Values.modelService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sms-app.model.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      version: {{ .Values.modelService.versionLabel | default .Values.app.versionLabel | quote }}
  template:
    metadata:
      labels:
        {{- include "sms-app.componentLabels" (dict "context" . "name" (include "sms-app.model.name" .) "component" "model") | nindent 8 }}
        version: {{ .Values.modelService.versionLabel | default .Values.app.versionLabel | quote }}
    spec:
      containers:
        - name: model-service
          image: "{{ .Values.modelService.image.repository }}:{{ .Values.modelService.image.tag }}"
          imagePullPolicy: {{ .Values.modelService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.modelService.containerPort }}
          env:
            - name: MODEL_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sms-app.fullname" . }}-config
                  key: MODEL_URL
            - name: DASHBOARD_VERSION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "sms-app.fullname" . }}-config
                  key: DASHBOARD_VERSION
          {{- if .Values.modelService.readinessProbe.tcpSocket }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.modelService.containerPort }}
            initialDelaySeconds: {{ .Values.modelService.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.modelService.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.modelService.livenessProbe.tcpSocket }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.modelService.containerPort }}
            initialDelaySeconds: {{ .Values.modelService.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.modelService.livenessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.modelService.volume.enabled }}
          volumeMounts:
            - name: model-storage
              mountPath: /app/models
          {{- end }}
      {{- if .Values.modelService.volume.enabled }}
      volumes:
        - name: model-storage
          hostPath:
            path: {{ .Values.modelService.volume.hostPath }}
            type: DirectoryOrCreate
      {{- end }}