apiVersion: v1
kind: Service
metadata:
  name: {{ include "sms-app.model.name" . }}-v1
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "sms-app.componentLabels" (dict "context" . "name" (printf "%s-v1" (include "sms-app.model.name" .)) "component" "model") | nindent 4 }}
spec:
  type: {{ .Values.modelService.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "sms-app.model.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    version: "v1"
  ports:
    - name: http
      port: {{ .Values.modelService.service.port }}
      targetPort: {{ .Values.modelService.containerPort }}
