{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "sms-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_PASSWORD: {{ required "secrets.smtpPassword is required when secrets.create=true" .Values.secrets.smtpPassword | quote }}
{{- end }}
