apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-app.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "sms-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_PASSWORD: "{{ .Values.secrets.smtpPassword }}"
