apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-model" (include "chart.fullname" .) }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: model
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.model.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: model
