{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sms-app.app.name" . }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace | default (.Values.namespace.name | default .Release.Namespace) }}
  labels:
    {{- include "sms-app.labels" . | nindent 4 }}
    {{ .Values.monitoring.serviceMonitor.labelKey }}: {{ .Values.monitoring.serviceMonitor.labelValue }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace.name | default .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sms-app.app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      path: {{ .Values.monitoring.paths.app }}
      interval: {{ .Values.monitoring.scrapeInterval }}
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_version]
          targetLabel: version
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
{{- end }}
