apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-app" (include "chart.fullname" .) }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
