# Helm implementation should use values.yaml for configuration
# This means it will replace the hardcoded values with placeholders, so it's fine to use them for now.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: sms-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: ghcr.io/doda2025-team17/app:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_SERVER_PORT
            - name: MODEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MODEL_URL
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASSWORD